[versions]
koin = "4.1.0"

[libraries]
core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }